configuration:
  - listen: 'localhost:9'
    outputs:
        graphite:
            - {host: 'localhost:1929'}
            - {host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
        loglocal: '/var/log/raxstat/localhost11.log'
        syslog: {host: 'localhost:1928', priority: 'LOG_INFO'}
  - listen: 'localhost:1'
    outputs:
        graphite:
            - {host: 'localhost:1929'}
            - {host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
        loglocal: '/var/log/raxstat/localhost11.log'
        syslog: {host: 'localhost:1928', priority: 'LOG_INFO'}
