logging: {file : '/tmp/raxstat.log' , level: DEBUG }
gigs:
  - listen: 'localhost:9993'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
