logging: {file : '/tmp/raxstat.log' , filelevel: DEBUG, consolelevel: DEBUG }
gigs:
  - listen: 'localhost:12201'
    outputs:
        graphite:
            - {project: 'test19' , host: 'graphite1:1929'}
            - {project: 'test19' , host: 'graphite2:1929'}
        riemann:
            - {host: '127.0.0.1:100'}
            - {host: '127.0.0.1:200'}
        udprepeater:
            - {host: '127.0.22.1:12202'}
  - listen: 'localhost:12202'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
  - listen: 'localhost:1242'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: 'localhost:13202'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: '127.1.1.1:1221'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: 'localhost:1222'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: '127.1.1.1:1223'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: 'localhost:1224'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: '127.1.1.1:1225'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
  - listen: 'localhost:1226'
    outputs:
        graphite:
            - {project: 'test19' , host: 'localhost:1929'}
            - {project: 'test19' , host: 'remote:1929'}
        riemann:
            - {host: 'localhost:100'}
            - {host: 'remote:200'}
        udprepeater:
            - {host: 'localhost:699'}
